# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cdef/tdebase-trinity-14.1.1/twin/compton-tde

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cdef/tdebase-trinity-14.1.1/twin/compton-tde

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cdef/tdebase-trinity-14.1.1/twin/compton-tde/CMakeFiles /home/cdef/tdebase-trinity-14.1.1/twin/compton-tde//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cdef/tdebase-trinity-14.1.1/twin/compton-tde/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compton-tde

# Build rule for target.
compton-tde: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compton-tde
.PHONY : compton-tde

# fast build rule for target.
compton-tde/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/build
.PHONY : compton-tde/fast

c2.o: c2.c.o
.PHONY : c2.o

# target to build an object file
c2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/c2.c.o
.PHONY : c2.c.o

c2.i: c2.c.i
.PHONY : c2.i

# target to preprocess a source file
c2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/c2.c.i
.PHONY : c2.c.i

c2.s: c2.c.s
.PHONY : c2.s

# target to generate assembly for a file
c2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/c2.c.s
.PHONY : c2.c.s

compton.o: compton.c.o
.PHONY : compton.o

# target to build an object file
compton.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/compton.c.o
.PHONY : compton.c.o

compton.i: compton.c.i
.PHONY : compton.i

# target to preprocess a source file
compton.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/compton.c.i
.PHONY : compton.c.i

compton.s: compton.c.s
.PHONY : compton.s

# target to generate assembly for a file
compton.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/compton.c.s
.PHONY : compton.c.s

dbus.o: dbus.c.o
.PHONY : dbus.o

# target to build an object file
dbus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/dbus.c.o
.PHONY : dbus.c.o

dbus.i: dbus.c.i
.PHONY : dbus.i

# target to preprocess a source file
dbus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/dbus.c.i
.PHONY : dbus.c.i

dbus.s: dbus.c.s
.PHONY : dbus.s

# target to generate assembly for a file
dbus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/dbus.c.s
.PHONY : dbus.c.s

opengl.o: opengl.c.o
.PHONY : opengl.o

# target to build an object file
opengl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/opengl.c.o
.PHONY : opengl.c.o

opengl.i: opengl.c.i
.PHONY : opengl.i

# target to preprocess a source file
opengl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/opengl.c.i
.PHONY : opengl.c.i

opengl.s: opengl.c.s
.PHONY : opengl.s

# target to generate assembly for a file
opengl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compton-tde.dir/build.make CMakeFiles/compton-tde.dir/opengl.c.s
.PHONY : opengl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... compton-tde"
	@echo "... c2.o"
	@echo "... c2.i"
	@echo "... c2.s"
	@echo "... compton.o"
	@echo "... compton.i"
	@echo "... compton.s"
	@echo "... dbus.o"
	@echo "... dbus.i"
	@echo "... dbus.s"
	@echo "... opengl.o"
	@echo "... opengl.i"
	@echo "... opengl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

